### ISSUE TITLE
Failed to start: Package subpath './v4' is not defined by "exports" in /home/pi/...  error

### ISSUE THREAD

**Issue by SCarns** [sbender9/signalk-cloud#11]
Code references /uuid/v4. I found v4.js in ~/.signalk/node_modules/uuid/dist/v4.js rather than ~/.signalk/node_modules/uuid/v4.js. Unsure, but could this be the fix? Or am I way off? This is in 64 bit openplotter with SK 1.43 & 1.44.

**Comment by AlanJHancock** [comment]
I got the same error today with a fresh install of 64 bit openplotter on Raspberry Pi4B 4GB could not fix it as the issue was too involved. 
So reinstalled signalK then installed cloud plugin again, all OK this time.

**Comment by seamaster101** [comment]
I also have the same issue. Is there information of how one can fix this problem?

**Comment by sbender9** [comment]
I don't know why this happens. Seen it before. Try reinstalling the plugin. Let me know if you need instructions.

**Comment by seamaster101** [comment]
I did reinstall 4 or 5 times. The plugin never starts. Always fails to start with the same error. JordanOn Mar 4, 2023, at 11:02, Scott Bender ***@***.***> wrote:﻿
I don't know why this happens. Seen it before. Try reinstalling the plugin. Let me know if you need instructions.

**Comment by seamaster101** [comment]
@sbender9 below is some more information from the log file. Maybe could give you some hints why is this happening and how its can be addresseed:
`Mar 08 05:34:25 Could not parse security config
Mar 08 05:34:25 ENOENT: no such file or directory, open '/data/conf/signalk/security.json'
Mar 08 05:34:33 signalk-cloud failed to start: Package subpath './v4' is not defined by "exports" in /data/conf/signalk/node_modules/uuid/package.json
Mar 08 05:34:33 Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /data/conf/signalk/node_modules/uuid/package.json at throwExportsNotFound (internal/modules/esm/resolve.js:299:9) at packageExportsResolve (internal/modules/esm/resolve.js:522:3) at resolveExports (internal/modules/cjs/loader.js:449:36) at Function.Module._findPath (internal/modules/cjs/loader.js:489:31) at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27) at Function.Module._load (internal/modules/cjs/loader.js:745:27) at Module.require (internal/modules/cjs/loader.js:961:19) at require (internal/modules/cjs/helpers.js:92:18) at Object.<anonymous> (/data/conf/signalk/node_modules/signalk-cloud/index.js:5:16) at Module._compile (internal/modules/cjs/loader.js:1072:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10) at Module.load (internal/modules/cjs/loader.js:937:32) at Function.Module._load (internal/modules/cjs/loader.js:778:12) at Module.require (internal/modules/cjs/loader.js:961:19) at require (internal/modules/cjs/helpers.js:92:18) at doRegisterPlugin (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:337:39) { code: 'ERR_PACKAGE_PATH_NOT_EXPORTED' }
Mar 08 05:34:36 signalk-server running at 0.0.0.0:3000`
Please try to help!

**Comment by seamaster101** [comment]
@SCarns @AlanJHancock @sbender9 
Found the fix:
run npm install uuid@^3.3.2 --save-dev
this fixes the problem

**Comment by martincaddick** [comment]
to be more precise
cd .signalk
and then run
npm install uuid@^3.3.2 --save-dev

**Comment by sbender9** [comment]
I just released a fix for this
