### ISSUE TITLE
Cloud server certificate has expired. 

### ISSUE THREAD

**Issue by seamaster101** [sbender9/signalk-cloud#25]
@sbender9  I noticed that I  can’t no longer login to the SignalK cloud server. When I went to the log I noticed this error message:
“ signalk-cloud:Error%20connecting%20to%20cloud%20server%20certificate%20has%20expired%20”
Is this certificate going to be renewed to be able to access the SignalK data remotely again?

**Comment by SL3Github** [comment]
I am having the same problem

**Comment by sbender9** [comment]
fixed now
