### ISSUE TITLE
Problem to access my data

### ISSUE THREAD

**Issue by romton843** [sbender9/signalk-cloud#6]
Hi, I'm sorry but everything worked fine up to this point: "With WilhelmSK, add a boat and point it to cloud.signalk.org. Go to Settings->Cloud and find your boat to view your data." I have no idea how to "add" a boat and can't find the Settings->Cloud.
Could someone please help me out?
Sorry to bother. 
Best regards. 
Romain Guimard

**Comment by sbender9** [comment]
Go to Settings -> Connections and add a Signal K Connections.

Enter a name a andcloud.signalk.org for Host and 80 for port.

Now go back to the top menu and tap on the new connection. Now you should see Settings -> Cloud

**Comment by romton843** [comment]
Hi, thanks to your guide I was able to create that connection but I can't find my boat in the list.
I'm not sure but it might be because I have a connection error in Signal K:
"error connecting to cloud server certificate has expired"
I tried to update the token but the error remains.
Any suggestions?
Thank you for your great work by the way .
Best regards.
Romain

**Comment by romton843** [comment]
It all worked out finally. Thank you so much.
