### ISSUE TITLE
Victron Cerbo GX - Signalk Cloud - Plug-in failed to start 

### ISSUE THREAD

**Issue by londine** [sbender9/signalk-cloud#7]
Hello, 
I have SignalK on Victron Venus os Large image , on a Cerbo GX,     I have recently tried to install the SignalK Cloud plug in , ( mainly for WilhelmSk while off the vessel ).    When i restart the Cerbo after install , i see on the SK dashboard the Signalk Cloud failed to start could not find module uuid/v4 ..........     I have me token already ... but not able to put it in the plug-in config as this “ signalk Clould “ does not appear in the Plug in list. 

Thank you

**Comment by seamaster101** [comment]
@londine did you get that issue resolved? if you did, please give me some hints how to fix?
